name: build-pipeline
run-name: Run ${{github.run_number}} on ref ${{github.ref_name}}, user ${{ github.actor }}
on: 
  push:
    branches:
      - 'add-workflow'
env:
  PYTHON_VENV: ${{ github.workspace }}/.venv
  APP_SRC_DIR: ${{ github.workspace }}/src/hello-app
jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Starting Job ${{github.job}}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install main dependencies
        run: |
          python -m pip install --upgrade pip
          pip install venv
      - name: Setup Python virtual environment
        run: |
          python -m venv ${{env.PYTHON_VENV}}
          source ${{env.PYTHON_VENV}}/bin/activate
      - name: Install job specific dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 build
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ${{env.APP_SRC_DIR}} --count --show-source --max-line-length=80 --statistics
      - name: Build pacakage
        run: |
          python -m build ${{env.APP_SRC_DIR}}
      - name: List created packages
        run: |
          ls ${{env.APP_SRC_DIR}}/dist
      - name: Cleanup environment
        run: |
          deactivate
          rm -rf ${{env.APP_SRC_DIR}}/dist
          rm -rf ${{env.PYTHON_VENV}}
      - run: |
          echo "Job ${{github.job}} finished with status ${{ job.status }}."
