name: build-pipeline
run-name: Run ${{github.run_number}} on commit ${{github.ref_name}}, user ${{ github.actor }}
on: 
  push:
    branches:
      - 'add-workflow'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting Job ${{github.job}}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get cwd and github workspace
        run: |
          pwd && dir ${{ github.workspace }}
      - run: echo "Job finished with status ${{ job.status }}."
