name: build-pipeline
run-name: Run ${{github.run_number}} on ref ${{github.ref_name}}, user ${{ github.actor }}
on: 
  push:
    branches:
      - 'add-workflow'
env:
  PYTHON_VENV: ${{ github.workspace }}/.venv
  APP_SRC_DIR: ${{ github.workspace }}/src/hello-app
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Starting Job ${{github.job}}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pipenv'
      - name: Install main dependencies
        run: |
          python3 -m pip install pipenv
      - name: Setup Python virtual environment
        run: |
          pipenv install
      - name: Install job specific dependencies
        run: |
          pipenv install flake8 build
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ${{env.APP_SRC_DIR}} --count --show-source --max-line-length=80 --statistics
      - name: Build pacakage
        run: |
          which python
          python -m build ${{env.APP_SRC_DIR}}
      - name: List created packages
        run: |
          ls ${{env.APP_SRC_DIR}}/dist
      - name: Cleanup environment
        run: |
          rm -rf ${{env.APP_SRC_DIR}}/dist
          pipenv uninstall --all
          pipenv --rm
      - run: |
          echo "Job ${{github.job}} finished with status ${{ job.status }}."
